name: eeg_encoding
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python Environment
  - python=3.13.7
  - pip

  # Deep Learning (PyTorch + CUDA 12.4)
  - pytorch
  - torchvision
  - pytorch-cuda=12.4

  # Core Scientific Computing
  - numpy=2.2.6
  - scipy=1.16.2
  - pandas=2.3.2
  - scikit-learn=1.7.2
  - statsmodels=0.14.6
  - matplotlib=3.10.6
  - pillow=11.3.0

  # Other Tools and Dependencies
  - tqdm=4.67.1